FROM andremarquesdev/aguarela-cypress-tests-base:1.0.0

# install Edge dependencies
RUN apt-get -y install apt-transport-https software-properties-common
# import Microsoft GPG Key
RUN wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt-key add -
# enable Microsoft Edge Repo
RUN add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
# install Edge
RUN apt-get -y install microsoft-edge-beta
