name: Build, test and deploy to production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # runs "every wednesday at 15h GMT" (https://crontab.guru)
    - cron: "0 14 * * 3"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [14.17.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run linter
        run: yarn lint

  cypress-chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.17.6-slim-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.17.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: chrome
          build: yarn build
          command: yarn cypress:test:chrome
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-chrome
          path: "**/*.diff.png"

  cypress-edge:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.17.6-slim-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.17.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: edge
          tag: edge
          build: yarn build
          command: yarn cypress:test:edge
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-edge
          path: "**/*.diff.png"

  cypress-firefox:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container:
      image: cypress/browsers:node14.17.6-slim-chrome100-ff99-edge
      options: --user 1001
    strategy:
      matrix:
        node-version: [14.17.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: firefox
          tag: firefox
          build: yarn build
          command: yarn cypress:test:firefox
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-firefox
          path: "**/*.diff.png"

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [cypress-chrome, cypress-firefox, cypress-edge]
    if: github.ref == 'refs/heads/master' && github.event.schedule != '0 14 * * 3' && !contains(github.event.head_commit.message, 'chore')
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
