name: Build, test and deploy to production

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # runs "every wednesday at 15h GMT" (https://crontab.guru)
    - cron: "0 14 * * 3"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build app
        run: yarn build

      - name: Run unit tests
        run: yarn test

      - name: Run linter
        run: yarn lint

  cypress-chrome-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: chrome-desktop
          build: yarn build
          command: yarn cypress:test:chrome:desktop
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-chrome-desktop
          path: "**/*.diff.png"

  cypress-edge-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: edge
          tag: edge-desktop
          build: yarn build
          command: yarn cypress:test:edge:desktop
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-edge-desktop
          path: "**/*.diff.png"

  cypress-firefox-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container:
      image: cypress/browsers:node14.19.0-chrome100-ff99-edge
      options: --user 1001
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: firefox
          tag: firefox-desktop
          build: yarn build
          command: yarn cypress:test:firefox:desktop
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-firefox-desktop
          path: "**/*.diff.png"

      - name: Retry on error
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: echo('Retry')

  cypress-chrome-mobile:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          tag: chrome-mobile
          build: yarn build
          command: yarn cypress:test:chrome:mobile
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-chrome-mobile
          path: "**/*.diff.png"

  cypress-edge-mobile:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: edge
          tag: edge-mobile
          build: yarn build
          command: yarn cypress:test:edge:mobile
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-edge-mobile
          path: "**/*.diff.png"

  cypress-firefox-mobile:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build
    container:
      image: cypress/browsers:node14.19.0-chrome100-ff99-edge
      options: --user 1001
    strategy:
      matrix:
        node-version: [14.18.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: firefox
          tag: firefox-mobile
          build: yarn build
          command: yarn cypress:test:firefox:mobile
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODEMAILER_SEND_EMAIL_FROM: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM }}
          NODEMAILER_SEND_EMAIL_FROM_PASS: ${{ secrets.NODEMAILER_SEND_EMAIL_FROM_PASS }}
          NODEMAILER_SEND_EMAIL_TO: ${{ secrets.NODEMAILER_SEND_EMAIL_TO }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-diff-snapshots-firefox-mobile
          path: "**/*.diff.png"

      - name: Retry on error
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: echo('Retry')

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      [
        cypress-chrome-desktop,
        cypress-firefox-desktop,
        cypress-edge-desktop,
        cypress-chrome-mobile,
        cypress-firefox-mobile,
        cypress-edge-mobile,
      ]
    if: github.ref == 'refs/heads/master' && github.event.schedule != '0 14 * * 3' && !contains(github.event.head_commit.message, 'chore') && !contains(github.event.head_commit.message, 'test') && !contains(github.event.head_commit.message, 'docs') && !contains(github.event.head_commit.message, 'ci')
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        run: npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
