name: Run Cypress tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.22.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          browser: chrome
          headless: true
          config-file: cypress.json
          build: yarn build
          start: yarn cypress:test:chrome
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
